# Generated by Django 3.2.13 on 2022-06-15 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_auto_20220511_1819'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entry',
            name='place',
        ),
        migrations.RemoveField(
            model_name='entry',
            name='srno',
        ),
        migrations.AddField(
            model_name='entry',
            name='faceMatched',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='entry',
            name='inDb',
            field=models.BooleanField(default=False),
        ),
    ]
