# Generated by Django 3.2.13 on 2022-06-15 10:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_auto_20220615_1627'),
    ]

    operations = [
        migrations.RenameField(
            model_name='entry',
            old_name='Name',
            new_name='name',
        ),
    ]
