# Generated by Django 3.2.13 on 2022-06-16 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_rename_name_entry_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='face',
            name='picclick',
            field=models.BooleanField(default=False),
        ),
    ]
